services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hbo-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - hbo_sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  hbo_sql_data:
